CREATE OR REPLACE VIEW PERSONS AS
SELECT ID,
       INSURANCE_ID,
       LAST_NAME,
       FIRST_NAME,
       ADDRESS,
       CITY,
       TO_CHAR(ROWVERSION,'YYYY-MM-DD-HH24.MI.SS') ROWVERSION,
       ROWID  objid
FROM PERSONS_TAB
WITH read only;
